# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 2 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
title: Jet

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Jet

author:
  name: Jun Jet T.
  email: taijunjet@hotmail.com
  github: jjshoots
  linkedin: jun-jet-t-97932b113
  instagram: jj_shoots
  bio:
    Engineering Student.<br>
    UAV Enthusiast.<br>
    Dreamer.


BASE_PATH: /jet.io

plugins:
  - jekyll-paginate
